# LLM
AZURE_OPENAI_API_BASE: (API_BASE) # https://XXX
AZURE_OPENAI_API_DEPLOY_NAME: (API_DEPLOY_NAME) # gpt-4o
AZURE_OPENAI_API_VERSION: (API_VERSION)  # 2024-02-01
OPENAI_API_KEY: (API_KEY) # XXXXXXX..